import { defineField, defineType } from "sanity";

export default defineType({
  name: "property",
  title: "Property",
  type: "document",
  groups: [
    { name: "content", title: "Content" },
    { name: "details", title: "Stay Details" },
    { name: "media", title: "Media" },
  ],
  fields: [
    defineField({
      name: "name",
      title: "Property Name",
      type: "string",
      validation: (Rule) => Rule.required(),
      group: "content",
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "name", maxLength: 96 },
      validation: (Rule) => Rule.required(),
      group: "content",
    }),
    defineField({
      name: "city",
      title: "City",
      type: "reference",
      to: [{ type: "city" }],
      validation: (Rule) => Rule.required(),
      group: "content",
    }),
    defineField({
      name: "tagline",
      title: "Tagline",
      type: "string",
      group: "content",
    }),
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      options: {
        list: [
          { title: "Available", value: "available" },
          { title: "Coming Soon", value: "coming-soon" },
        ],
      },
      initialValue: "available",
      group: "content",
    }),
    defineField({
      name: "shortDescription",
      title: "Short Description",
      type: "text",
      rows: 2,
      group: "content",
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "array",
      of: [{ type: "text", rows: 3 }],
      description: "One entry per paragraph.",
      group: "content",
    }),
    defineField({
      name: "coverImage",
      title: "Cover Image",
      type: "image",
      options: { hotspot: true },
      group: "media",
    }),
    defineField({
      name: "gallery",
      title: "Gallery",
      type: "array",
      of: [{ type: "image", options: { hotspot: true } }],
      group: "media",
    }),
    defineField({
      name: "guestCapacity",
      title: "Guest Capacity",
      type: "number",
      group: "details",
    }),
    defineField({
      name: "bedrooms",
      title: "Bedrooms",
      type: "number",
      group: "details",
    }),
    defineField({
      name: "bathrooms",
      title: "Bathrooms",
      type: "number",
      group: "details",
    }),
    defineField({
      name: "amenities",
      title: "Amenities",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "checkIn",
      title: "Check-in Time",
      type: "string",
      group: "details",
    }),
    defineField({
      name: "checkOut",
      title: "Check-out Time",
      type: "string",
      group: "details",
    }),
    defineField({
      name: "highlights",
      title: "Highlights",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "neighbourhood",
      title: "Neighbourhood",
      type: "text",
      rows: 2,
      group: "details",
    }),
    defineField({
      name: "mapLink",
      title: "Map Link",
      type: "url",
      group: "details",
    }),
    defineField({
      name: "houseRules",
      title: "House Rules",
      type: "array",
      of: [{ type: "string" }],
      group: "details",
    }),
    defineField({
      name: "tags",
      title: "Stay Tags",
      type: "array",
      of: [{ type: "string" }],
      options: {
        list: ["Couple Friendly", "Work Stay", "Family Stay", "Group Stay"],
      },
      group: "details",
    }),
    defineField({
      name: "pricing",
      title: "Pricing (optional — leave empty until confirmed)",
      type: "object",
      fields: [
        { name: "startingFrom", title: "Starting From (INR)", type: "number" },
        { name: "note", title: "Note", type: "string" },
      ],
      group: "details",
    }),
  ],
  preview: {
    select: { title: "name", subtitle: "status", media: "coverImage" },
  },
});
